.Dd $Mdocdate$
.Dt crapsum 1
.Os
.Sh NAME
.Nm crapsum ,
.Nm crapsum256 ,
.Nm crapsum512
.Nd generate meaningless SHA checksums
.Sh SYNOPSIS
.Nm crapsum256
.Pp
.Nm crapsum512
.Sh DESCRIPTION
.Nm
generates random hexadecimal sequences which resemble SHA checksums.
.Sh AUTHORS
This program is maintained by
.An Varik Valefor
.Aq varikvalefor@aol.com .
