.Dd $Mdocdate$
.Dt sendjunk 1
.Os
.Sh NAME
.Nm sendjunk
.Nd encrypt and send crap to an e-mail address
.Sh SYNOPSIS
.Nm sendjunk
.Ar address publickey
.Op Ar subjectline
.Sh DESCRIPTION
.Nm
generates junk text, encrypts this text with PGP public key
.Ar publickey ,
then sends this encrypted text to e-mail address
.Ar address .
.Pp
.Ar publickey
actually contains a PGP fingerprint, as opposed to a
.Qq proper
PGP public key.
.Pp
.Ar address
follows the format
.Sy [USERNAME]@[DOMAIN] .
.Pp
If argument
.Ar subjectline
is passed to
.Nm ,
then the subject line of the message which
.Nm
sends is equal to
.Ar subjectline .
Otherwise, the subject line shall default to
.Qq (URGENT) Patch for Security Vulnerability .
.Sh AUTHORS
This program is maintained by
.An Varik Valefor
.Aq varikvalefor@aol.com .
