.Dd $Mdocdate$
.Dt ten 1
.Os
.Sh NAME
.Nm ten
.Nd use lots of processing power and RAM
.Sh SYNOPSIS
.Nm ten
.Sh DESCRIPTION
.Nm
maps a useless function to a list whose computation is very
CPU-and-memory-intensive.
.Pp
.Nm
is essentially a simpler version of
.Xr stress 1 .
.Sh AUTHORS
This program is maintained by
.An Varik Valefor
.Aq varikvalefor@aol.com .
